description: >
  This is base docker executor that all other language specific executors inherits.
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: 2020.01
    description: >
      Pick a specific image variant:
      https://github.com/CircleCI-Public/cimg-base#tagging-scheme
    type: string
